name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test-in-parallel:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      # To wygeneruje folder 'blob-report' z dziwnymi plikami w ≈õrodku
      run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

    - name: Upload blob report to GitHub Actions Artifacts
      # Wysy≈Çamy wyniki do "chmury tymczasowej" GitHuba
      if: always() # Wykonaj nawet jak testy padnƒÖ!
      uses: actions/upload-artifact@v4
      with:
        # Nadajemy unikalnƒÖ nazwƒô dla ka≈ºdego kawa≈Çka (np. blob-report-1, blob-report-2)
        name: blob-report-${{ matrix.shardIndex }}
        path: blob-report
        retention-days: 1

  # --- NOWE ZADANIE: SPRZƒÑTACZ ---
  merge-reports: 
    # To zadanie ruszy DOPIERO jak wszystkie shardy sko≈ÑczƒÖ (sukcesem lub pora≈ºkƒÖ)
    if: always() 
    needs: [test-in-parallel]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci

    - name: Download blob reports from GitHub Actions Artifacts
      # Pobieramy wszystkie paczki, kt√≥re zaczynajƒÖ siƒô od 'blob-report'
      uses: actions/download-artifact@v4
      with:
        pattern: blob-report-*
        merge-multiple: true
        path: all-blob-reports

    - name: Merge into HTML Report
      # Magiczna komenda Playwrighta
      run: npx playwright merge-reports --reporter html ./all-blob-reports

    - name: Upload Final HTML Report
      # Wysy≈Çamy gotowy, sklejony raport HTML, ≈ºeby≈õ m√≥g≈Ç go pobraƒá
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 14
        
    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact for Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: playwright-report # Folder z HTMLem

    # ZMIANA 2: Wrzucamy na serwer
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
    - name: Send Slack Notification
      if: always() 
      # Wy≈õlij nawet jak testy pad≈Çy (a zw≈Çaszcza wtedy!)
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }} # Sukces czy Pora≈ºka?
        notify_when: 'failure,success'
        notification_title: 'Raport Test√≥w Automatycznych (Playwright)'
        message_format: '{emoji} *{workflow}* {status_message} w {duration_format}. <{repo_url}|Zobacz Kod> lub <https://emdabljuuuu.github.io/playwright-lab/|üëâ ZOBACZ RAPORT ONLINE>'
        footer: 'Zbudowano przez GitHub Actions'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}